controller_list:
    - name: arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      joints:
          - oberon7/azimuth
          - oberon7/shoulder
          - oberon7/elbow
          - oberon7/roll
          - oberon7/pitch
          - oberon7/wrist
    - name: hand_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      joints:
          - oberon7/finger_left_joint
          - oberon7/finger_tip_left_joint
          - oberon7/finger_right_joint
          - oberon7/finger_tip_right_joint
