controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - oberon7/azimuth
      - oberon7/shoulder
      - oberon7/elbow
      - oberon7/roll
      - oberon7/pitch
      - oberon7/wrist
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - oberon7/finger_left_joint
      - oberon7/finger_tip_left_joint
      - oberon7/finger_right_joint
      - oberon7/finger_tip_right_joint
initial:  # Define initial robot poses per group
#  - group: arm
#    pose: home

  []
